server:
  port: 719
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    #password: root
    password: UMBs_6eNCk2TKkD
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  global-config:
    db-config:
      table-prefix: hit_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# debug: true

#logging:
#  file:
#    name: server.log
#  logback:
#    rolling policy:
#      max-file-size: 10MB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
logging:
  file:
    name: server.log
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rolling-policy:
      max-file-size: 10MB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log




